# Generated by Django 3.1.2 on 2020-10-09 18:44


from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historical', '0002_enable_timescaledb'),
    ]

    operations = [
    ]
