# Generated by Django 3.1.2 on 2020-10-09 16:46

from dbinfo import models
from django.db import migrations


def create_or_replace_table_info(apps, schema_editor):
    models.TableInfo.create_or_replace()


def drop_table_info(apps, schema_editor):
    models.TableInfo.drop()


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_or_replace_table_info,
            reverse_code=drop_table_info),
    ]
