# Generated by Django 3.1.3 on 2020-12-15 12:28

import dbinfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbinfo', '0002_create_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('table_name', models.TextField(help_text='Table name of the table', primary_key=True, serialize=False, verbose_name='table name')),
                ('is_hypertable', models.BooleanField(help_text='Indicates if the table is a timescaleDB hypertable', verbose_name='is hypertable')),
                ('table_size', models.PositiveBigIntegerField(help_text='Disk space used by table data', verbose_name='table size')),
                ('index_size', models.PositiveBigIntegerField(help_text='Disk space used by indexes', verbose_name='index size')),
                ('total_size', models.PositiveBigIntegerField(help_text='Total disk space used by the table (data + indexes)', verbose_name='total size')),
            ],
            options={
                'verbose_name': 'Table Information',
                'verbose_name_plural': 'Tables Information',
                'db_table': 'tables_info',
                'managed': False,
            },
            bases=(dbinfo.models.ViewMixin, models.Model),
        ),
    ]
