# TAGS
ALARM       = "alarm"
COMPUTED    = "computed"
IODATA      = "iodata"
PARAM       = "param"
BASIC       = "basic"
RESERVED    = "reserved"

AIR_HEATER  = "air heater"
ALARM_CFG   = "alarm settings"
C2H4        = "C2H4"
CO2         = "CO2"
ENABLED     = "enabled"
FORCED      = "forced"
GAS_BALANCE = "gas balance"
HUMIDITY    = "humidity"
PID         = "pid"
SENSOR      = "sensor"
SETTINGS    = "settings"
SYSTEM      = "system"
TEMPERATURE = "temperature"