# Generated by Django 3.1.6 on 2021-02-09 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0005_auto_20210114_1341'),
        ('historical', '0007_create_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_historical_data', 'Can view historical data'), ('can_view_events', 'Can view event')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
