# Generated by Django 3.1.6 on 2021-03-09 16:03

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historical', '0009_create_settings_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortedMeasurementsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', core.fields.SortOrderField(default=0, verbose_name='Sort')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historical.measurement')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historical.settings')),
            ],
            options={
                'unique_together': {('settings', 'measurement')},
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='default_measurements',
            field=models.ManyToManyField(help_text='List of measurements to include by default in historical data view', through='historical.SortedMeasurementsList', to='historical.Measurement', verbose_name='Default historical measurements'),
        ),
    ]
