# Generated by Django 3.1.2 on 2020-11-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldroom',
            options={'permissions': (('can_view_cold_room_params', 'View cold room parameters'), ('can_change_cold_room_params', 'Change cold room parameters')), 'verbose_name': 'cold room', 'verbose_name_plural': 'cold rooms'},
        ),
        migrations.RemoveField(
            model_name='coldroom',
            name='zone',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
