# Generated by Django 3.1.3 on 2020-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0002_delete_model_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldroom',
            name='enable_C2H4_proportional_ctrl',
            field=models.BooleanField(default=True, help_text='enables C2H4 proportional control option', verbose_name='C2H4 proportional control'),
        ),
        migrations.AddField(
            model_name='coldroom',
            name='enable_CO2_proportional_ctrl',
            field=models.BooleanField(default=True, help_text='enables CO2 proportional control option', verbose_name='CO2 proportional control'),
        ),
    ]
