# Generated by Django 3.1.3 on 2020-12-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0003_auto_20201126_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldroom',
            options={'ordering': ['name'], 'permissions': (('can_view_cold_room_params', 'View cold room parameters'), ('can_change_cold_room_params', 'Change cold room parameters')), 'verbose_name': 'cold room', 'verbose_name_plural': 'cold rooms'},
        ),
    ]
