# Generated by Django 3.1.3 on 2021-01-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0004_auto_20201215_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldroom',
            name='enable_C2H4_measurement',
            field=models.BooleanField(default=True, help_text='enables C2H4 measurement', verbose_name='C2H4 measurement'),
        ),
        migrations.AddField(
            model_name='coldroom',
            name='enable_CO2_measurement',
            field=models.BooleanField(default=True, help_text='enables CO2 measurement', verbose_name='CO2 measurement'),
        ),
        migrations.AddField(
            model_name='coldroom',
            name='enable_humidity_measurement',
            field=models.BooleanField(default=True, help_text='enables humidity measurement', verbose_name='humidity measurement'),
        ),
        migrations.AddField(
            model_name='coldroom',
            name='enable_temperature_measurement',
            field=models.BooleanField(default=True, help_text='enables temperature measurement', verbose_name='temperature measurement'),
        ),
    ]
