# Generated by Django 3.1.6 on 2021-02-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0005_auto_20210114_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_cold_rooms_summary', 'Can view cold rooms summary'), ('can_view_cold_room_params', 'Can view cold room params'), ('can_view_cold_room_detail', 'Can view cold room detail'), ('can_edit_cold_room_control_options', 'Can edit cold room control options')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
