# Generated by Django 3.1.6 on 2021-02-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0006_custom_views_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldroom',
            options={'ordering': ['name'], 'verbose_name': 'cold room', 'verbose_name_plural': 'cold rooms'},
        ),
    ]
