# Generated by Django 3.1.6 on 2021-03-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0007_remove_duplicated_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldroom',
            name='enable_selector',
            field=models.BooleanField(default=True, help_text='enables selector', verbose_name='Selector'),
        ),
    ]
