# Generated by Django 3.1.6 on 2021-03-04 11:46

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cold_rooms', '0008_coldroom_enable_selector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldroom',
            options={'ordering': ('sort_order',), 'verbose_name': 'cold room', 'verbose_name_plural': 'cold rooms'},
        ),
        migrations.AddField(
            model_name='coldroom',
            name='sort_order',
            field=core.fields.SortOrderField(default=0, verbose_name='Sort'),
        ),
    ]
