# Generated by Django 3.1.2 on 2020-11-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommsPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_read_vars_tagged_as_alarm', 'Can read variables tagged as alarm'), ('can_write_vars_tagged_as_alarm', 'Can write variables tagged as alarm'), ('can_read_vars_tagged_as_computed', 'Can read variables tagged as computed'), ('can_write_vars_tagged_as_computed', 'Can write variables tagged as computed'), ('can_read_vars_tagged_as_iodata', 'Can read variables tagged as iodata'), ('can_write_vars_tagged_as_iodata', 'Can write variables tagged as iodata'), ('can_read_vars_tagged_as_param', 'Can read variables tagged as param'), ('can_write_vars_tagged_as_param', 'Can write variables tagged as param'), ('can_read_vars_tagged_as_reserved', 'Can read variables tagged as reserved'), ('can_write_vars_tagged_as_reserved', 'Can write variables tagged as reserved')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
