# Generated by Django 3.1.2 on 2020-11-06 11:38

from django.db import migrations


def creat_predefined_groups(apps, schema_editor):
    from comms.permissions import PredefinedGroups
    PredefinedGroups.create()

def delete_predefined_groups(apps, schema_editor):
    from comms.permissions import PredefinedGroups
    PredefinedGroups.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            creat_predefined_groups,
            reverse_code=delete_predefined_groups),
    ]
