# Generated by Django 3.1.3 on 2020-12-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_create_predefined_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commspermissions',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_read_vars_tagged_as_C2H4', 'Can read variables tagged as C2H4'), ('can_write_vars_tagged_as_C2H4', 'Can write variables tagged as C2H4'), ('can_read_vars_tagged_as_CO2', 'Can read variables tagged as CO2'), ('can_write_vars_tagged_as_CO2', 'Can write variables tagged as CO2'), ('can_read_vars_tagged_as_air heater', 'Can read variables tagged as air heater'), ('can_write_vars_tagged_as_air heater', 'Can write variables tagged as air heater'), ('can_read_vars_tagged_as_alarm', 'Can read variables tagged as alarm'), ('can_write_vars_tagged_as_alarm', 'Can write variables tagged as alarm'), ('can_read_vars_tagged_as_alarm settings', 'Can read variables tagged as alarm settings'), ('can_write_vars_tagged_as_alarm settings', 'Can write variables tagged as alarm settings'), ('can_read_vars_tagged_as_basic', 'Can read variables tagged as basic'), ('can_write_vars_tagged_as_basic', 'Can write variables tagged as basic'), ('can_read_vars_tagged_as_computed', 'Can read variables tagged as computed'), ('can_write_vars_tagged_as_computed', 'Can write variables tagged as computed'), ('can_read_vars_tagged_as_enabled', 'Can read variables tagged as enabled'), ('can_write_vars_tagged_as_enabled', 'Can write variables tagged as enabled'), ('can_read_vars_tagged_as_forced', 'Can read variables tagged as forced'), ('can_write_vars_tagged_as_forced', 'Can write variables tagged as forced'), ('can_read_vars_tagged_as_gas balance', 'Can read variables tagged as gas balance'), ('can_write_vars_tagged_as_gas balance', 'Can write variables tagged as gas balance'), ('can_read_vars_tagged_as_humidity', 'Can read variables tagged as humidity'), ('can_write_vars_tagged_as_humidity', 'Can write variables tagged as humidity'), ('can_read_vars_tagged_as_iodata', 'Can read variables tagged as iodata'), ('can_write_vars_tagged_as_iodata', 'Can write variables tagged as iodata'), ('can_read_vars_tagged_as_param', 'Can read variables tagged as param'), ('can_write_vars_tagged_as_param', 'Can write variables tagged as param'), ('can_read_vars_tagged_as_pid', 'Can read variables tagged as pid'), ('can_write_vars_tagged_as_pid', 'Can write variables tagged as pid'), ('can_read_vars_tagged_as_reserved', 'Can read variables tagged as reserved'), ('can_write_vars_tagged_as_reserved', 'Can write variables tagged as reserved'), ('can_read_vars_tagged_as_sensor', 'Can read variables tagged as sensor'), ('can_write_vars_tagged_as_sensor', 'Can write variables tagged as sensor'), ('can_read_vars_tagged_as_settings', 'Can read variables tagged as settings'), ('can_write_vars_tagged_as_settings', 'Can write variables tagged as settings'), ('can_read_vars_tagged_as_system', 'Can read variables tagged as system'), ('can_write_vars_tagged_as_system', 'Can write variables tagged as system'), ('can_read_vars_tagged_as_temperature', 'Can read variables tagged as temperature'), ('can_write_vars_tagged_as_temperature', 'Can write variables tagged as temperature')]},
        ),
    ]
