# Generated by Django 3.1.6 on 2021-02-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_auto_20201215_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_view_comms_data', 'Can view communication data'), ('can_set_working_mode', 'Can set working mode'), ('can_acknowledge_alarms', 'Can acknowledge alarms'), ('can_accept_messages', 'Can accept messages'), ('can_export_memory_map', 'Can export memory map')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
