{
 "title": "Sample dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "coldRoom",
    "label": "Cold Room",
    "query": "SELECT name FROM cold_rooms_coldroom"
   },
   {
    "name": "floatMeasurement",
    "label": "Float Measurement",
    "query": "SELECT name FROM historical_measurement WHERE type = 'float'"
   },
   {
    "name": "integerMeasurement",
    "label": "Integer Measurement",
    "query": "SELECT name FROM historical_measurement WHERE type = 'int'"
   },
   {
    "name": "booleanMeasurement",
    "label": "Boolean Measurement",
    "query": "SELECT name FROM historical_measurement WHERE type = 'bool'"
   },
   {
    "name": "alarm",
    "label": "Alarm",
    "query": "SELECT name FROM historical_alarm"
   }
  ]
 },
 "panels": [
  {
   "title": "${floatMeasurement:raw} @ ${coldRoom:raw}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  --ts::timestamp as time,\n  m.name as metric,\n  value\nFROM historical_floatmeasurementdata\nINNER JOIN cold_rooms_coldroom As c ON c.id = cold_room_id\nINNER JOIN historical_measurement As m ON m.id = measurement_id\nWHERE $__timeFilter(ts) AND c.name = '${coldRoom:raw}' AND m.name = '${floatMeasurement:raw}'\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "${integerMeasurement:raw} @ ${coldRoom:raw}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  m.name as metric,\n  value\nFROM historical_integermeasurementdata\nINNER JOIN cold_rooms_coldroom As c ON c.id = cold_room_id\nINNER JOIN historical_measurement As m ON m.id = measurement_id\nWHERE $__timeFilter(ts) AND c.name = '${coldRoom:raw}' AND m.name = '${integerMeasurement:raw}'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "${booleanMeasurement:raw} @ ${coldRoom:raw}",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  m.name as metric,\n  value::integer\nFROM historical_booleanmeasurementdata\nINNER JOIN cold_rooms_coldroom As c ON c.id = cold_room_id\nINNER JOIN historical_measurement As m ON m.id = measurement_id\nWHERE $__timeFilter(ts) AND c.name = '${coldRoom:raw}' AND m.name = '${booleanMeasurement:raw}'\nORDER BY 1\n"
    }
   ]
  }
 ]
}