{
 "title": "Sample auto-switch dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "coldRoom",
    "label": "Cold Room",
    "query": "SELECT name FROM cold_rooms_coldroom"
   },
   {
    "name": "floatMeasurement",
    "label": "Float Measurement",
    "query": "SELECT name FROM historical_measurement WHERE type = 'float'"
   },
   {
    "name": "integerMeasurement",
    "label": "Integer Measurement",
    "query": "SELECT name FROM historical_measurement WHERE type = 'int'"
   },
   {
    "name": "booleanMeasurement",
    "label": "Boolean Measurement",
    "query": "SELECT name FROM historical_measurement WHERE type = 'bool'"
   },
   {
    "name": "alarm",
    "label": "Alarm",
    "query": "SELECT name FROM historical_alarm"
   }
  ]
 },
 "panels": [
  {
   "title": "${floatMeasurement:raw} @ ${coldRoom:raw}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Misc" }
   ],
   "targets": [
    {
     "rawSql": "WITH RECURSIVE params (POINTS, Ts, ts_from, ts_to, cold_room, measurement, bucket_time) as (\n\tVALUES (400, INTERVAL '0.5 sec',\n\t  -- now(), now() - INTERVAL '1 min',\n\t  $__timeTo()::timestamptz, $__timeFrom()::timestamptz,\n\t  (SELECT id FROM cold_rooms_coldroom WHERE name='${coldRoom:raw}'),\n\t  (SELECT id FROM historical_measurement WHERE name='${floatMeasurement:raw}'),\n\t  INTERVAL '0 sec'\n\t)\n\tUNION ALL\n\tSELECT POINTS, Ts, ts_from, ts_to, cold_room, measurement, GREATEST(\n\t\t (ts_from - ts_to) / (POINTS - 1), Ts\n\t)\n\tFROM params WHERE bucket_time = INTERVAL '0 sec'\n)\nSELECT q.* FROM (\n  SELECT\n  \ttime_bucket(bucket_time, d.ts) AS time,\n  \t-- $__timeFrom()::timestamptz as from, $__timeTo()::timestamptz as to,\n  \tavg(d.value) as value, min(d.value), max(d.value)\n  \t-- avg(d.value) - stddev_pop(d.value) as lower_sigma,\n  \t-- avg(d.value) + stddev_pop(d.value) as upper_sigma\n  \t-- stddev(d.value), count(d.*)\n   FROM historical_floatmeasurementdata as d, params\n  WHERE bucket_time > INTERVAL '0 sec'\n    AND cold_room_id = cold_room \n    AND measurement_id = measurement\n    AND d.ts BETWEEN ts_to AND ts_from\n  GROUP BY time\n  ORDER BY time DESC\n  LIMIT 400\n) as q\n-- necessary to prevent 'data outside time range' message\nWHERE $__timeFilter(q.time) \n"
    }
   ]
  },
  {
   "title": "${integerMeasurement:raw} @ ${coldRoom:raw}",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH RECURSIVE params (POINTS, Ts, ts_from, ts_to, cold_room, measurement, bucket_time) as (\n\tVALUES (400, INTERVAL '0.5 sec',\n\t  $__timeTo()::timestamptz, $__timeFrom()::timestamptz,\n\t  (SELECT id FROM cold_rooms_coldroom WHERE name='${coldRoom:raw}'),\n\t  (SELECT id FROM historical_measurement WHERE name='${integerMeasurement:raw}'),\n\t  INTERVAL '0 sec'\n\t)\n\tUNION ALL\n\tSELECT POINTS, Ts, ts_from, ts_to, cold_room, measurement, GREATEST(\n\t\t (ts_from - ts_to) / (POINTS - 1), Ts\n\t)\n\tFROM params WHERE bucket_time = INTERVAL '0 sec'\n)\nSELECT q.* FROM (\n  SELECT\n  \ttime_bucket(bucket_time, d.ts) AS time,\n  \tavg(d.value) as value, min(d.value), max(d.value)\n   FROM historical_integermeasurementdata as d, params\n  WHERE bucket_time > INTERVAL '0 sec'\n    AND cold_room_id = cold_room \n    AND measurement_id = measurement\n    AND d.ts BETWEEN ts_to AND ts_from\n  GROUP BY time\n  ORDER BY time DESC\n  LIMIT 400\n) as q\n-- necessary to prevent 'data outside time range' message\nWHERE $__timeFilter(q.time) "
    }
   ]
  },
  {
   "title": "${booleanMeasurement:raw} @ ${coldRoom:raw}",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(ts),\n  m.name as metric,\n  value::integer\nFROM historical_booleanmeasurementdata\nINNER JOIN cold_rooms_coldroom As c ON c.id = cold_room_id\nINNER JOIN historical_measurement As m ON m.id = measurement_id\nWHERE $__timeFilter(ts) AND c.name = '${coldRoom:raw}' AND m.name = '${booleanMeasurement:raw}'\nORDER BY 1\n"
    }
   ]
  }
 ]
}