# Generated by Django 3.1.6 on 2021-03-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
