# Generated by Django 3.1.6 on 2021-03-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': 'contactos'},
        ),
    ]
