# Generated by Django 3.1.6 on 2021-02-09 10:54

from django.db import migrations


def create_singleton_instances(apps, schema_editor):
    from alerts import models
    models.EmailNotificationSettings.load()
    models.TelegramNotificationSettings.load()

def delete_singleton_instances(apps, schema_editor):
    from alerts import models
    models.EmailNotificationSettings.load().delete()
    models.TelegramNotificationSettings.load().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_allow_blank_telgram_receivers'),
    ]

    operations = [
        migrations.RunPython(
            create_singleton_instances,
            reverse_code=delete_singleton_instances),
    ]
